from .general import web_search, calculator, current_time
from .files import python_interpreter, list_uploaded_files
from .dev import json_formatter, hash_generator, encoding_tool, timestamp_converter, qrcode_generator, sql_formatter
from .office import (
    excel_to_csv_from_upload,
    csv_to_excel_from_upload,
    markdown_to_html,
    word_to_pdf_from_upload,
    pdf_to_word_from_upload,
    excel_to_pdf_from_upload,
    table_basic_profile_from_upload,
    table_value_counts_from_upload,
    table_correlation_from_upload,
    table_filter_query_from_upload,
    table_outliers_from_upload,
    table_pivot_from_upload,
    table_chart_histogram_from_upload,
    table_chart_scatter_from_upload,
    table_chart_line_from_upload,
    table_chart_bar_from_upload,
)
from .image import (
    image_resize_base64,
    image_convert_base64,
    image_crop_base64,
    image_compress_base64,
    image_rotate_base64,
    image_add_text_watermark_base64,
    image_add_image_watermark_base64,
    image_remove_watermark_base64,
    image_upload_to_base64,
    image_crop_upload,
    image_compress_upload,
    image_rotate_upload,
    image_add_text_watermark_upload,
    image_add_image_watermark_upload,
    image_remove_watermark_upload,
    image_auto_remove_watermark_upload,
)

def get_tools():
    return [
        web_search, 
        calculator, 
        current_time, 
        python_interpreter, 
        list_uploaded_files,
        json_formatter,
        hash_generator,
        encoding_tool,
        timestamp_converter,
        qrcode_generator,
        sql_formatter,
        excel_to_csv_from_upload,
        csv_to_excel_from_upload,
        markdown_to_html,
        word_to_pdf_from_upload,
        pdf_to_word_from_upload,
        excel_to_pdf_from_upload,
        table_basic_profile_from_upload,
        table_value_counts_from_upload,
        table_correlation_from_upload,
        table_filter_query_from_upload,
        table_outliers_from_upload,
        table_pivot_from_upload,
        table_chart_histogram_from_upload,
        table_chart_scatter_from_upload,
        table_chart_line_from_upload,
        table_chart_bar_from_upload,
        image_resize_base64,
        image_convert_base64,
        image_crop_base64,
        image_compress_base64,
        image_rotate_base64,
        image_add_text_watermark_base64,
        image_add_image_watermark_base64,
        image_remove_watermark_base64,
        image_upload_to_base64,
        image_crop_upload,
        image_compress_upload,
        image_rotate_upload,
        image_add_text_watermark_upload,
        image_add_image_watermark_upload,
        image_remove_watermark_upload,
        image_auto_remove_watermark_upload,
    ]
